# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [2]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [3]:
import numpy as np

**2. Print the numpy version and the configuration**

**3. Create a 1D array of zeros of size 10 of type float32**

**4. Print the memory size of the array below**

In [ ]:
Z = np.zeros((32,12))
# Include your solution below

**5. Create a 1D array with values ranging from 10 to 58**

In [8]:
# There are two ways to do so one is with arange function which
# makes a one-dimensional array ranging from the first number to the second number
# excluding the last one. So to include 58, I have specified 59 as the second number.
q5_array = np.arange(10, 59)
print(q5_array)

# The other way to do the same is to use linespace in which
# you only specify the starting point, the ending point, and
# the number of array elements.
# Uncomment the following three lines to see the two methods produce the same result.

# q5_array2 = np.linspace(10, 58, 49)
# print(q5_array2)
# print(f"Are the two arrays produce the same result: {(q5_array == q5_array2).all()}")

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [ ]:
a = np.arange(10)
# Include your solution below

**7. Create a 3x3 matrix with values ranging from 0 to 8**

**8. Create a 3x3 identity matrix**

**9. Find and print the maximum values of each column in the array below** 

In [13]:
Z = np.random.random((10,11))
# Include your solution below

# There is a built-in function for NumPy arrays named max with which
# you can calculate the maximum element of a given array by specifying
# the axis along which you are willing to obtain the max. For this example
# as we want to calculate the max for each column, we specify 0 for the axis and the 
# resulting array should have 11 elements.
column_max = Z.max(axis=0)
print(column_max)

[0.89757799 0.88427998 0.86435689 0.84263344 0.8012704  0.87873247
 0.93519646 0.86965549 0.91510755 0.9554091  0.7892738 ]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [ ]:
Z = np.ones((5,5))
# Include your solution below

**12. Extract the integer part of the random array of positive numbers below**

In [16]:
Z = np.random.uniform(0,10,10)
# Include your solution below
# print(f"The original array is: {Z}\n") #Uncomment this line to see the original array.

# To extract the integer part of an array element,
# we can simply cast elements to integer 
# by calling the astype function and specifying int as the function input.
q12_answer = Z.astype(int)
print(q12_answer)

[3 4 5 0 0 1 6 6 1 9]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

**15. Create a random vector of size 10 and sort it**

**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below


**17. Create random vector of size 10 and replace the maximum value by 0**

**18. Find the nearest value from a given value (z) in an array (Z)**

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below

**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [ ]:
Z = np.arange(5)[::-1]
# Include your solution below


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below



**21. Swap the first and second rows of the 2D array below**

In [17]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below

# This could be done by specifying the rows' number 
# and changing their order and assigning the matrix to itself.
W[[0, 1]] = W[[1, 0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="https://github.com/rmsouza01/ENEL645/blob/master/Figures/bbox.png?raw=1" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [26]:
def moving_average(x,N = 3):
    #define your function here

    # My approach to this problem is making a 2D matrix with three elements
    # in each row and then computing the mean of each row.
    row_num = int(len(x) / N) # Calculate the number of rows.

    # Reshaping the original array to make a 2D matrix and 
    # making a deep copy of the original array.
    new_array = x.copy().reshape(row_num, N)

    return new_array.mean(axis=1) # Calculate the mean along the axis 1 which means for each row.
    
# If we are not sure that the number of array elements is a multiple of N, we should use the following function.
# def moving_average(x,N = 3):
#     #define your function here

#     # My approach to this problem is making a 2D matrix with three elements
#     # in each row and then computing the mean of each row.
#     row_num = int(len(x) / N) # Calculate the number of rows.
#     diff = len(x) - row_num * N
#     if diff != 0:
#         # Adding zeros to original array to make it a multiple of N and 
#         # making a deep copy of it.
#         x_copy = np.append(x.copy(), np.zeros(N - diff, dtype= int))

#         # Reshaping the original array to make a 2D matrix.
#         new_array = x_copy.reshape(row_num + 1, N)

#         return new_array.mean(axis=1) # Calculate the mean along the axis 1 which means for each row.
#     else:
#         # Reshaping the original array to make a 2D matrix and 
#         # making a deep copy of the original array.
#         new_array = x.copy().reshape(row_num, N)

#         return new_array.mean(axis=1) # Calculate the mean along the axis 1 which means for each row.  


a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below

**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    