# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [ ]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [ ]:
print(np.__version__) #printing numpy version
print(np.show_config()) #printing numpy configuration

**3. Create a 1D array of zeros of size 10 of type float32**

In [ ]:
np.zeros(10, dtype=np.float32) #np.zeros creates an array, the first parameter denotes the size of array and the second parameter (dtype) denotes the data type.

**4. Print the memory size of the array below**

In [29]:
Z = np.zeros((32,12))
# Include your solution below
# Print the memory size of the array using size and itemsize attributes of NumPy array. 
# size: This attribute gives the number of elements present in the NumPy array. itemsize: This attribute gives the memory size of one element of NumPy array in bytes

print("The memory size of the array: %d bytes" % (Z.size * Z.itemsize)) 

The memory size of the array: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

**6. Reverse the order of the values in the vector (first element becomes last)**

In [ ]:
a = np.arange(10)
# Include your solution below

**7. Create a 3x3 matrix with values ranging from 0 to 8**

**8. Create a 3x3 identity matrix**

In [ ]:
np.identity(3) #np.identity is used to create a square identity matrix i.e. all elements zero with 1's in the main diagonal. The parameter '3' is the size of the square array.

**9. Find and print the maximum values of each column in the array below** 

In [ ]:
Z = np.random.random((10,11))
# Include your solution below

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [ ]:
a = np.ones((7,7) ) #create a 7x7 array of ones
a[1:-1,1:-1]=0 #using indexing change the central values to 0
print(a) #print the solution

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [30]:
Z = np.ones((5,5))

# Include your solution below
print("Initial array:\n", Z)
print("-------------------------------\n")

# First Option
# The array padding transformation sets a dimension in an array to a new size. The goal of this transformation is to reduce the number of memory system conflicts.
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print("First option for padding with 0:\n", Z)
print("-------------------------------\n")

# Second Option
# Fancy indexing is like the simple indexing we've already seen, but we pass arrays of indices in place of single scalars. This allows us to very quickly access and modify complicated subsets of an array's values.
# Fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print("Second option for padding with 0:\n", Z)

Initial array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-------------------------------

First option for padding with 0:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
-------------------------------

Second option for padding with 0:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [ ]:
Z = np.random.uniform(0,10,10)
# Include your solution below

**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [ ]:
z = np.tile(np.arange(0,5),(5,1)) #use Numpy tile function to create a 5x5 matrix where each row values ranging from 0 to 4
print(z) #print solution

**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [ ]:
#linspace returns 11 (given by third parameter) evenly spaced values in the range of 1 (given by first parameter) to 1 (second paramater).
#to get 10 values between 0 and 1, we get 11 values and then discard the first value so as to not include the starting value i.e. 0, and use the endpoint parameter to not include endpoint i.e. 1.
x = np.linspace(0,1,11, endpoint=False)[1:] 
x

**15. Create a random vector of size 10 and sort it**

In [15]:
Z = np.random.random(10)
Z.sort() # Note: This method returns a copy of the array, leaving the original array unchanged. To save the result in a new variable, the following code should be used: Z_sortet = Z.sort()
print(Z)

[0.01070194 0.36623697 0.53151562 0.54978297 0.73605361 0.78717738
 0.79503016 0.84613128 0.93503537 0.99566965]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below


**17. Create random vector of size 10 and replace the maximum value by 0**

In [ ]:
z = np.random.random(10) #create a random vector size 10
print(z) #print the random vector
z[z.argmax()] = 0 #use argmax to find the maximum value, use indexing to replace with 0
print(z) #print z where the max value has been replaced with 0

**18. Find the nearest value from a given value (z) in an array (Z)**

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below

**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [19]:
Z = np.arange(5)[::-1]
# Include your solution below

numberOf_zeros = 3 # number of zeros we want to add between each value
Z_final = np.zeros(len(Z) + (len(Z)-1)*(numberOf_zeros)) # creating a new array with the number of zeros needed to be add to the primary array
Z_final[::numberOf_zeros+1] = Z # filling the array with original numbers and 3 consecutive zeros between each value
print(Z_final)

[4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
#np.einsum takes i,j,k (the 3 axes of A) and i,j (the 2 axes) of B as inputs, common notations i, j in both A & B denote that i,j matrix of A is multiplied elementwise with i,j matrix of B. This is repeated for each k (depth) of A. 
C = np.einsum('ijk,ij->ijk', A, B)  
print(C.shape,'\n', C)

**21. Swap the first and second rows of the 2D array below**

In [ ]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="https://github.com/rmsouza01/ENEL645/blob/master/Figures/bbox.png?raw=1" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    y,x = np.where(img == 1) #coordinate arrays (y and x) are returned denoting all location with '1' in the image
    r1, c1 = min(x), min(y) #min values from both x and y coordinate arrays are calculated for top left coordinates of bounding box
    r2, c2 = max(x), max(y) #max values from both x and y coordinate arrays are calculated for bottom right coordinates of bounding box
    return (r1,c1),(r2,c2)


from PIL import Image, ImageDraw

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

#displaying image with bounding box
a, b = bbox(img)
im = Image.open('../Figures/bin_image.png')
draw = ImageDraw.Draw(im)
draw.rectangle([(a[0], a[1]), (b[0], b[1])], outline='red')
plt.imshow(im)


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
def moving_average(x,N = 3):
    #define your function here
    return

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6]) #create an array containing the occurance of each number in the vector
print(C) #print the bincount of the vector
# Include your solution here
A = np.repeat(np.arange(len(C)),C) #create an array of evenly spaced values teh same size as length C, repeat values in A using the bincount
print(np.bincount(A)) #print the bincount of array A

**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below

**26. Write a function to return the n largest values of an array** 

In [27]:
def nlargest(a,n = 5):
    # Include your solution here
    
    # Slower computation
    # For getting n-largest values from a NumPy array we have to first sort the NumPy array using numpy.argsort() function of NumPy then applying slicing concept with negative indexing.
    #result = Z[np.argsort(Z)[-n:]]

    # Faster computation
    # Newer NumPy versions (1.8 and up) have a function called argpartition for this. Argpartition runs in linear time, O(n), using the introselect algorithm.
    result = (Z[np.argpartition(-Z,n)[:n]])
    
    return result

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

[9995 9999 9996 9997 9998]
