# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [17]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [18]:
import numpy as np

**2. Print the numpy version and the configuration**

**3. Create a 1D array of zeros of size 10 of type float32**

**4. Print the memory size of the array below**

In [ ]:
Z = np.zeros((32,12))
# Include your solution below

**5. Create a 1D array with values ranging from 10 to 58**

**6. Reverse the order of the values in the vector (first element becomes last)**

In [21]:
a = np.arange(10)
# Include your solution below

b=a[::-1]                                 #Shallow Copy
print(' Original order of a = ',a)        # print original a values
print(' Reverse  order of a = ',b)        # print revers a values

 Original order of a =  [0 1 2 3 4 5 6 7 8 9]
 Reverse  order of a =  [9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [3]:
a=np.arange(9) #creating list of values
a.shape=(3,3)  #change a shape 

print ('3x3 matrix  with values ranging from 0 to 8 =',"\n",a)
    

3x3 matrix  with values ranging from 0 to 8 = 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

**9. Find and print the maximum values of each column in the array below** 

In [ ]:
Z = np.random.random((10,11))
# Include your solution below

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [ ]:
Z = np.ones((5,5))
# Include your solution below

**12. Extract the integer part of the random array of positive numbers below**

In [ ]:
Z = np.random.uniform(0,10,10)
# Include your solution below

**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

**15. Create a random vector of size 10 and sort it**

**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [22]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below



R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)

print('polar coordinates (R and T)',"\n")

print(R,"\n")
print(T,"\n")


polar coordinates (R and T) 

[0.81901182 0.9786099  1.16352461 0.46232155 0.33488068 0.95758647
 0.9800529  1.16372165 0.68693446 0.76113733] 

[0.74341438 1.12121072 0.800256   0.63660195 0.66358288 0.06549419
 1.43286468 0.59715355 1.40261572 0.1916181 ] 



**17. Create random vector of size 10 and replace the maximum value by 0**

**18. Find the nearest value from a given value (z) in an array (Z)**

In [14]:
Z = np.random.uniform(0,1,10) 
z = 0.5   
# Include your solution below


n = Z.flat[np.abs(Z - z).argmin()] 

print('array (Z) = \n',Z ,"\n")
print('given value (z) = ',z,"\n")


print('the nearest value from a given value (z) in an array (Z) =',n)


array (Z) = 
 [0.86793224 0.46925983 0.95320703 0.58785983 0.88547141 0.67246153
 0.92631898 0.71434156 0.41263703 0.55646839] 

given value (z) =  0.5 

the nearest value from a given value (z) in an array (Z) = 0.46925983099394775


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [ ]:
Z = np.arange(5)[::-1]
# Include your solution below


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below



**21. Swap the first and second rows of the 2D array below**

In [ ]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="https://github.com/rmsouza01/ENEL645/blob/master/Figures/bbox.png?raw=1" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
def moving_average(x,N = 3):
    #define your function here
    return

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [16]:
Z = np.random.randint(0,10,50)
# Include your solution below

print('Original array:\n',Z,"\n")
print("Most frequent value in the above array:")
print(np.bincount(Z).argmax())

Original array:
 [4 2 9 2 0 9 0 5 0 4 2 3 5 1 7 9 0 7 0 1 4 0 2 6 4 0 5 5 9 3 9 4 1 9 1 4 7
 1 8 8 8 9 3 9 4 5 6 8 9 6] 

Most frequent value in the above array:
9


**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    