In [11]:
# 6. Reverse the order of the values in the vector (first element becomes last)

import numpy as np # import numpy library

a = np.arange(10) # creating list of values

print(' Original order of a = ',a)        # print original a values
print(' Reverse  order of a = ',a[::-1])  # print revers a values

 Original order of a =  [0 1 2 3 4 5 6 7 8 9]
 Reverse  order of a =  [9 8 7 6 5 4 3 2 1 0]


In [28]:
# 7. Create a 3x3 matrix with values ranging from 0 to 8

a=np.arange(9) #creating list of values
a.shape=(3,3)  #change a shape 

print ('3x3 matrix  with values ranging from 0 to 8 =',"\n",a)
    

3x3 matrix  with values ranging from 0 to 8 = 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
# 16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]



R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)

print('polar coordinates (R and T)',"\n")

print(R,"\n")
print(T,"\n")




polar coordinates (R and T) 

[1.01311939 0.64545554 1.15757352 0.87874193 0.37923437 0.42018888
 0.87158291 0.92498398 1.22762438 0.64552787] 

[1.17380069 1.21465984 0.86005819 0.51005252 0.84188626 1.0837277
 0.15220041 0.4048211  0.72009308 1.20198807] 



In [43]:
# 18 Find the nearest value from a given value (z) in an array (Z)

Z = np.random.uniform(0,1,10) # Creating array (Z)
z = 0.5                       # given value (z)


# Find the nearest value from a given value (z) in an array (Z)
n = Z.flat[np.abs(Z - z).argmin()] 

print('the nearest value from a given value (z) in an array (Z) =',n)




the nearest value from a given value (z) in an array (Z) = 0.5183121715930158


In [64]:
#25. Find the most frequent value in the array below?

Z = np.random.randint(0,10,50)

print("Original array:")
print(Z)
print("\n")
print("Most frequent value in the above array:")
print(np.bincount(Z).argmax())

Original array:
[1 2 8 7 2 3 5 1 3 3 7 9 0 0 7 3 8 3 4 8 4 1 0 6 1 2 3 7 0 1 6 0 8 9 3 8 8
 4 8 3 6 8 9 4 6 7 7 8 0 4]


Most frequent value in the above array:
8
